/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "nnwejwsdjhctxndzcnvk"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5ud2Vqd3NkamhjdHhuZHpjbnZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE1OTE3MDksImV4cCI6MjA3NzE2NzcwOX0.vCOPF6hlfyZE5P21-l8iBam-qD19Zu1x2HNOFAtArz4"